### ISSUE TITLE
Compilation issues 

### ISSUE THREAD

**Issue by matthewrwright** [sudomesh/disaster-radio#32]
Not sure whether to raise this as a disaster-radio issue or a LoRaLayer2 issue - apologies if I've pushed it in the wrong place.

On make:

`In file included from ./firmware/esp32_ttgo/console.cpp:2:0:
./libs/LoRaLayer2/src/LoRaLayer2.h: In member function 'void consoleClass::lr(char (*)[8])':
./libs/LoRaLayer2/src/LoRaLayer2.h:74:10: error: 'void LL2Class::printRoutingTable()' is private
     void printRoutingTable();
          ^
./firmware/esp32_ttgo/console.cpp:21:31: error: within this context
         LL2.printRoutingTable();
                               ^
make: *** [Makefile:262: /tmp/mkESP/main_ttgo-lora32-v1/console.cpp.o] Error 1
`

Resolved by moving the definition in libs/LoRaLayer2/src/LoRaLayer2.h from private to public.

**Comment by paidforby** [comment]
Good catch! This really an issue with [LoRaLayer2](https://github.com/sudomesh/LoRaLayer2), this is an OK place to inquire about it though. Looks like I made some local changes that library that I never pushed to the repo. I pushed those changes [here](https://github.com/sudomesh/LoRaLayer2/commit/5b59547f400cdeccef7acacc9833f2f4502b8d46) and updated `fetch_deps` to checkout the latest. Make sure you always pull the latest LoRaLayer2, since I'm actively making changes to that repo. Likewise, I'll make sure to always push any necessary updates to the libraries being used.
